package main

const dispatcherFileContent string = "" +
	`var Dispatcher = require('flux').Dispatcher;
module.exports = new Dispatcher();`

const appJSFileContent string = "" +
	`var React = require('react');

var App = React.createClass({
  render(){
    return (
      <div>
        <h1>A Demo Page Generated By Flux Generator</h1>
        <p>Start to develop your own app now !</p>
      </div>
    ); 
  }
});

module.exports = App;`

const mainJSFileContent string = "" +
	`var React = require('react');
	var App = require('./components/App.js');
	
	React.render(<App />, document.getElementById('container'));`

const webpackConfigFileContent string = "" +
	`module.exports = {
  entry: "./scripts/main.js",
  output: {
    path: "./build",
    filename: "bundle.js"
  },
  module: {
   loaders: [
     { test: /\.jsx?$/, loader: "react-hot!babel"}
    ]
  }
};`

const indexHTMLFileContent string = "" +
	`<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Index</title>
<body>
  <div id="container"></div>
  <script src="./bundle.js"></script>
</body>
</head>
</html>
`

func packageJSONFileContent(appName string, authorName string) string {
	fileContent := "" +
		`{
  "name": "` + appName + `",
  "version": "1.0.0",
  "description": "",
  "main": "./bundle.js",
  "author": "` + authorName + `",
  "license": "ISC",
  "dependencies": {
    "babel-core": "*",
    "babel-loader": "*",
    "flux": "*",
    "object-assign": "*",
    "react": "*",
    "react-hot-loader": "*",
    "webpack": "*"
  }
}`

	return fileContent
}
